CLASS zclnov05_graph_01 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
      constructor.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
    TYPES:
      BEGIN OF cty_distance,
        from TYPE string,
        to   TYPE string,
        dist TYPE string,
      END OF cty_distance.
    CLASS-DATA:
      ct_edge TYPE SORTED TABLE OF cty_distance WITH NON-UNIQUE KEY from.
    METHODS:
      graph_dfs.
ENDCLASS.


CLASS zclnov05_graph_01 IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
    DATA(lv_str) = 'Testing'. "meaningless, to test in-line declaration
    out->write( lv_str && | "graph travesal with DFS or BFS" in ABAP|
        )->write( |Don't worry. I will use HANA Graph later.|
        )->write( cl_abap_char_utilities=>newline
        ).

    out->write( ct_edge )->write( cl_abap_char_utilities=>newline ).

    LOOP AT ct_edge ASSIGNING FIELD-SYMBOL(<fs>) WHERE from = 'Seattle'.
      out->write( <fs>-from && cl_abap_char_utilities=>horizontal_tab &&
        <fs>-to && cl_abap_char_utilities=>horizontal_tab &&
        <fs>-dist ).
    ENDLOOP.
  ENDMETHOD.


  METHOD constructor. "fill ct_edge
    DATA: lw_edge TYPE cty_distance.

** data generated by ChatGPT
    DATA(lv_str_csv) =
        'New York,Los Angeles,2778;' &&
        'Chicago,Houston,940;' &&
        'San Francisco,Seattle,1094;' &&
        'Miami,Atlanta,663;' &&
        'Washington DC,Boston,394;' &&
        'Dallas,Austin,195;' &&
        'Phoenix,Denver,586;' &&
        'Detroit,Minneapolis,539;' &&
        'Charlotte,Raleigh,172;' &&
        'Philadelphia,Pittsburgh,305;' &&
        'Las Vegas,San Diego,332;' &&
        'Nashville,Memphis,210;' &&
        'Kansas City,St Louis,238;' &&
        'Indianapolis,Cincinnati,111;' &&
        'New Orleans,Atlanta,466;' &&
        'Orlando,Miami,230;' &&
        'Houston,San Antonio,197;' &&
        'Baltimore,Philadelphia,101;' &&
        'Cleveland,Columbus,143;' &&
        'Milwaukee,Minneapolis,337;' &&
        'Portland,Seattle,173;' &&
        'Austin,San Antonio,79;' &&
        'Salt Lake City,Denver,519;' &&
        'San Diego,Los Angeles,120;' &&
        'Sacramento,San Francisco,90;' &&
        'Louisville,Indianapolis,114;' &&
        'Tampa,Miami,248;' &&
        'Seattle,Vancouver,141;' &&
        'Albuquerque,Denver,449;' &&
        'Jacksonville,Miami,346;' &&
        'Hartford,Boston,102;' &&
        'Raleigh,Atlanta,355;' &&
        'Phoenix,Los Angeles,373;' &&
        'Chicago,Minneapolis,409;' &&
        'St Louis,Memphis,281;' &&
        'Detroit,Chicago,281;' &&
        'Denver,Dallas,663;' &&
        'San Francisco,Las Vegas,569;' &&
        'Charlotte,Atlanta,248;' &&
        'Boston,New Haven,139;' &&
        'Dallas,New Orleans,522;' &&
        'Philadelphia,New York,96;' &&
        'Seattle,Portland,173;' &&
        'Cleveland,Pittsburgh,133;' &&
        'Kansas City,Denver,601;' &&
        'San Antonio,Austin,132;' &&
        'Indianapolis,Chicago,181;' &&
        'Baltimore,Richmond,144;' &&
        'Phoenix,Albuquerque,422;' &&
        'Salt Lake City,Boise,303;' &&
        'Columbus,Cincinnati,107;'.
*    REPLACE ALL OCCURRENCES OF ';' IN lv_str_csv WITH cl_abap_char_utilities=>newline.

* The use of Class CL_RSDA_CSV_CONVERTER is not permitted in BTP Trial.
    SPLIT lv_str_csv AT ';' INTO TABLE DATA(lt_str).
    LOOP AT lt_str ASSIGNING FIELD-SYMBOL(<str>).
      CLEAR lw_edge.
      SPLIT <str> AT ',' INTO lw_edge-from lw_edge-to lw_edge-dist.
      INSERT lw_edge INTO TABLE ct_edge.

      DATA(lv_str) = lw_edge-from. "swap "from" and "to"
      lw_edge-from = lw_edge-to.
      lw_edge-to = lv_str.
      INSERT lw_edge INTO TABLE ct_edge.
    ENDLOOP.
  ENDMETHOD.


  METHOD graph_dfs.

  ENDMETHOD.
ENDCLASS.
